### ISSUE TITLE
Login "username" and "password" entries span outside of box element

### ISSUE THREAD

**Issue by christophermilian** [Nvall024/anirate-website#5]
In account.html. The "username" and "password" entries when selected span outside of the designated box element. Need to reduce the increase value.

**Comment by christophermilian** [comment]
![Screenshot (22)](https://user-images.githubusercontent.com/43291127/100475962-6878ef00-30b2-11eb-85c2-f95aee88b8fa.png)

**Comment by Nvall024** [comment]
fixed

**Comment by Nvall024** [comment]
fixed
